# Generated by Django 3.0.4 on 2020-05-06 21:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0009_auto_20200506_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date', models.DateField(verbose_name='date reported')),
                ('time', models.TimeField(verbose_name='time reported')),
                ('support_indicator', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('TR', 'Προς Εισαγωγή'), ('RE', 'Εισηγμένο'), ('TS', 'Προς Επίλυση'), ('SO', 'Λυμένο'), ('CA', 'Ακυρωμένο')], default='TR', max_length=2)),
                ('incident_slug', models.SlugField(blank=True)),
                ('problem_kind', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reporter.Problems')),
                ('user_email', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reporter.User_Res')),
            ],
            options={
                'verbose_name_plural': 'Incident',
            },
        ),
        migrations.DeleteModel(
            name='Incidences',
        ),
    ]
